[PHP]
post_max_size = 100M
upload_max_filesize = 100M
variables_order = EGPCS
memory_limit = 512M

[opcache]
opcache.enable_cli=1
opcache.jit=off
opcache.jit_buffer_size=0

[xdebug]
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.client_host = ${XDEBUG_CLIENT_HOST}
xdebug.client_port = ${XDEBUG_CLIENT_PORT}
xdebug.idekey = VSCODE
